name 'ubuntu14'
maintainer 'Nathan Winther'
maintainer_email 'hello@nathanwinther.info'
license 'all_rights'
description 'Installs/Configures ubuntu14'
long_description 'Installs/Configures ubuntu14'
version '0.1.0'
